config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/profskipulag/ST540104:
      branch: main
      repo: https://github.com/profskipulag/ST540104
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/profskipulag/ST540104 git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-fuchsia-dolphin.sh
        container: qc.acc_snippy-malachite-bird
  QC.Doc:
    repos:
      github.com/profskipulag/ST540104 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-pumpkin-hyena.sh
        container: qc.doc_cheeky-red-nightingale
      github.com/profskipulag/ST540104 git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-sapphire-havanese.sh
        container: qc.doc_muzzy-salmon-squirt
      github.com/profskipulag/ST540104 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-carmine-eagle.sh
        container: qc.doc_beady-thistle-magpie
  QC.Lic:
    repos:
      github.com/profskipulag/ST540104 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pumpkin-sheep.sh
        container: qc.lic_scummy-malachite-worm
  QC.Sec:
    repos:
      github.com/profskipulag/ST540104 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-platinum-horse.sh
        container: qc.sec_skanky-bistre-duck
  QC.Sty:
    repos:
      github.com/profskipulag/ST540104 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-copper-ferret.sh
        container: qc.sty_grumpy-thistle-tuatara
  QC.Uni:
    repos:
      github.com/profskipulag/ST540104 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-asparagus-seahorse.sh
        container: qc.uni_muggy-cerise-orangutan
  QC.Ver:
    repos:
      github.com/profskipulag/ST540104 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-red-bear.sh
        container: qc.ver_goopy-buff-hare
timeout: 5400
